* Data

- www/images/chem-nyan/chem-nyan.gif
  this works derived from:
  © 2015 /g/
  according to:

  https://archive.org/details/M00GNU

  released under Creative Commons Attribution-ShareAlike 3.0

  and © laobc

  according to https://openclipart.org/detail/26692/chemistry-flask
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

  hence it is released under Creative Commons Attribution-ShareAlike 3.0

- www/images/ghs-pictograms/*.png
  data/ghs-pictograms/*.eps
  www/images/adr-pictograms/*.png
  data/adr-pictograms/*.eps
  Got from http://www.unece.org/trans/danger/publi/ghs/pictograms.html
  The United Nations Economic Commission for Europe (UNECE)

- www/images/icon-ghs-prec.png
  derived from
  © kg
  according to https://openclipart.org/detail/104263/warning-sign
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- data/letter-header.png
  © 2016 Universita' degli Studi di Palermo
  Released under GPL version 3

- www/images/lab-logo.svg
  © 2016 Universita' degli Studi di Palermo
  released under GPL version 3

- www/images/error-bullet.png
  © molumen
  according to https://openclipart.org/detail/109/red-round-error-warning-icon
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/hand.png
  www/images/icon-lending-remove.png
  derived from works © Anonymous
  according to https://openclipart.org/detail/12799/hand
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-add-msds-pdf.png
  www/images/icon-msds-pdf.png
  www/images/icon-add-struct-file.png
  www/images/icon-struct-file.png
  derived from works © leandrosciola
  according to https://openclipart.org/detail/171857/icon-pdf-a%C2%8Dcone
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-delete.png
  © dagobert83
  according to https://openclipart.org/detail/1645/cancel
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-ext-link.png
  © pnx
  according to https://openclipart.org/detail/202731/external-link-icon
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/info-bullet
  © kuba
  according to https://openclipart.org/detail/15472/information-icons-set-3
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/location-add-icon.png
  www/images/location-add-icon.png
  © snodnipper
  according to https://openclipart.org/detail/177208/map-location
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/sorry.png
  derived from © laobc
  according to https://openclipart.org/detail/26692/chemistry-flask
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/favicon.ico
  derived from © laobc
  according to https://openclipart.org/detail/26692/chemistry-flask
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/tag-w-string
  © crisg
  according to https://openclipart.org/detail/188919/name-tag
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-edit.png
  © crisg
  according to https://openclipart.org/detail/116083/write-document-icon
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-gen-qrcode.png
  © dexMilano
  according to https://openclipart.org/detail/132709/qrcode-reader
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/ghs-pictograms/none.png
  © uroesch
  according to https://openclipart.org/detail/185355/happy-cloud
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/prohibition.png
  © yves_guillou
  according to https://openclipart.org/detail/10982/prohibition7
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/activate.png
  © TzeenieWheenie
  according to https://openclipart.org/detail/10940/red-+-green-ok-not-ok-icons
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-sensor.png
  © sixsixfive
  according to https://openclipart.org/detail/212119/sensors
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-positive.png
  derived from
  © adlerweb
  according to https://openclipart.org/detail/257086/positive-emblem-icon
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- www/images/icon-negative.png
  derived from
  © adlerweb
  according to https://openclipart.org/detail/257087/negative-emblem-icon
  released under CC0 https://creativecommons.org/publicdomain/zero/1.0/

- data/font.afm
  Copyright (URW)++,Copyright 1999 by (URW)++ Design & Development
  Released under (GNU General Public License)

- www/css/images/*
  jQuery UI - v1.11.4 - 2015-07-19
  http://jqueryui.com

  Copyright 2015 jQuery Foundation and other contributors; Licensed MIT

- www/css/font-awesome-*/fonts/*

  according to http://fontawesome.io/license/

  © 2016 Dave Gandy
  released under SIL Open Font License (OFL)
  http://scripts.sil.org/OFL

- www/images/ajax-loader.gif

  got       from       http://ajaxload.info/      released       under
  http://www.wtfpl.net/faq/ license according to the website above

- scripts/populate-db.sql
  derived from
  - https://it.wikipedia.org/wiki/Frasi_H
  - https://it.wikipedia.org/wiki/Consigli_P
  - https://en.wikipedia.org/wiki/Lists_of_UN_numbers (and subpages)

    released under
    Attribuzione - Condividi allo stesso modo 3.0 Unported (CC BY-SA 3.0)
    https://creativecommons.org/licenses/by-sa/3.0/deed.it

- data/font.ttf

  Source: https://savannah.gnu.org/projects/freefont/

  Copyright: 2002-2012, GNU Freefont contributors
  License: GPL-3+ with Special Font Exception

  License: GPL-3+ with Special Font Exception

  GNU FreeFont is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free  Software Foundation; either  version 3 of the  License, or
  (at your option) any later version.

  The fonts are distributed in the  hope that they will be useful, but
  WITHOUT  ANY   WARRANTY;  without  even  the   implied  warranty  of
  MERCHANTABILITY or  FITNESS FOR A  PARTICULAR PURPOSE.  See  the GNU
  General Public License for more details.

  You should  have received a copy  of the GNU General  Public License
  along  with  this  program;  if  not, write  to  the  Free  Software
  Foundation,  Inc.,  51  Franklin  Street, Fifth  Floor,  Boston,  MA
  02110-1301, USA.

  * Regarding the use of built font files.

  As a  special exception, if  you create  a document which  uses this
  font, and  embed this font or  unaltered portions of this  font into
  the  document, this  font does  not  by itself  cause the  resulting
  document  to be  covered by  the  GNU General  Public License.  This
  exception  does not  however invalidate  any other  reasons why  the
  document might be covered by the  GNU General Public License. If you
  modify this font,  you may extend this exception to  your version of
  the font, but you are not obligated to do so.  If you do not wish to
  do so, delete this exception statement from your version.

  * Clarification of exception, regarding intended use of embedded fonts

  The exception to the GNU General Public License for the GNU FreeFont
  software exempts a user that embeds  part or all of the GNU FreeFont
  software in a document, as well as subsequent users and distributors
  of  the  document,  from  complying  with the  GNU  GPL  under  some
  circumstances

  Specifically,  this  exemption applies  when  the  embedder has  not
  modified the GNU FreeFont software before embedding it. This is true
  even though portions of the software become part of the document

  Therefore  users of  fonts  released with  this  exception need  not
  concern themselves with the license terms to:

  Create a printable file using the fonts
  - Publish such a file
  - Redistribute such a file
  - Publicly display such a file
  - Print such a file or display it on the screen

  However anyone distributing the font software as software separately
  from the  document, even if the  way the font software  was obtained
  was to extract it from a document, would have to comply with the GNU
  GPL

  A modified version of the GNU FreeFont software must comply with the
  GNU  GPL It  may  optionally carry  the same  exception  as the  GNU
  FreeFont  software  itself,  and  we  recommend  releasing  modified
  versions that way. If it does, then users will likewise be permitted
  to embed  the modified version in  documents and be exempt  from the
  GNU GPL requirements on those documents

* Code
  - conditions.lisp
  - xml-utils.lisp
  - configuration-utils.lisp
  - quick_quicklisp.sh.in

  Are © 2013,2014,2015,2016 Valerio Benfante released under GNU GPL version
  3 or later

- string-utils.lisp
  ellipsize is derived from
  © Diogo Franco
  released under
  The MIT License (MIT)

  Copyright (c) 2016 Diogo Franco

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.

- math-utils.lisp
  - =*default-epsilon*=
  - with-epsilon
  - add-epsilon-rel
  - epsilon<=
  - epsilon>=
  - epsilon=

  derived from
  dawn of the Era: a tactical game.
  Copyright (C) 2015  cage

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

- jquery-ui.min.js
  jquery-ui.js
  http://jqueryui.com

  Includes: core.js,  widget.js, mouse.js,  position.js, draggable.js,
  droppable.js,     resizable.js,      selectable.js,     sortable.js,
  accordion.js, autocomplete.js,  button.js, datepicker.js, dialog.js,
  menu.js,   progressbar.js,  selectmenu.js,   slider.js,  spinner.js,
  tabs.js,  tooltip.js, effect.js,  effect-blind.js, effect-bounce.js,
  effect-clip.js,  effect-drop.js, effect-explode.js,  effect-fade.js,
  effect-fold.js,         effect-highlight.js,         effect-puff.js,
  effect-pulsate.js, effect-scale.js, effect-shake.js, effect-size.js,
  effect-slide.js, effect-transfer.js

  Copyright 2015 jQuery Foundation and other contributors; Licensed MIT

- jquery.js
  http://jquery.com/

  Includes Sizzle.js
  http://sizzlejs.com/

  Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors
  Released under the MIT license
  http://jquery.org/license

- sugar.js

  Sugar Library v1.4.1

  Freely distributable and licensed under the MIT-style license.
  Copyright (c) 2014 Andrew Plummer
  http://sugarjs.com/

- mustache.js

  Freely distributable and licensed under the MIT-style license.
  Copyright (c) 2016 Jan Lehnardt
  https://github.com/janl/mustache.js/


- jquery-ui.structure.css

  jQuery UI CSS Framework 1.11.4
  http://jqueryui.com

  Copyright jQuery Foundation and other contributors
  Released under the MIT license.
  http://jquery.org/license

  http://api.jqueryui.com/category/theming/


- jquery-ui.structure.min.css

  jQuery UI - v1.11.4 - 2015-07-19
  http://jqueryui.com
  Copyright 2015 jQuery Foundation and other contributors; Licensed MIT */


- jquery-ui.css
  jquery-ui.min.css

  http://jqueryui.com

  Includes:  core.css,  draggable.css,  resizable.css,  selectable.css,
  sortable.css,     accordion.css,    autocomplete.css,     button.css,
  datepicker.css,      dialog.css,      menu.css,      progressbar.css,
  selectmenu.css,   slider.css,  spinner.css,   tabs.css,  tooltip.css,
  theme.css

  Copyright 2015 jQuery Foundation and other contributors; Licensed MIT */

- jquery-ui.theme.css
  http://jqueryui.com

  Copyright jQuery Foundation and other contributors
  Released under the MIT license.
  http://jquery.org/license

- jquery-ui.theme.min.css

  http://jqueryui.com
  Copyright 2015 jQuery Foundation and other contributors; Licensed MIT */

- qrcode.js

  Copyright (c) 2009 Kazuhiko Arase

  URL: http://www.d-project.com/

  Licensed under the MIT license:
  http://www.opensource.org/licenses/mit-license.php

- www/css/font-awesome-*/css/*
  www/css/font-awesome-*/scss/*
  www/css/font-awesome-*/less/*

  © 2016 Dave Gandy

  according to http://fontawesome.io/license/

  Licensed under the MIT license:
  http://www.opensource.org/licenses/mit-license.php

- www/js/get-get.js
   got from http://stackoverflow.com/a/901144
   author jolly.exe https://stackoverflow.com/users/1045296/jolly-exe
   © jolly.exe released under creative commons
   Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)
   https://creativecommons.org/licenses/by-sa/3.0/

- sensors/gas/mq135.h
  This code derived from (c) 2016  G.Krocker (Mad Frog Labs)
  according to: https://github.com/GeorgK/MQ135 */
  licensed under GPLv3

- www/css/anim.css
  www/css/style.css

  Contains code:
  © Ana Travas
  http://animista.net
  original license FreeBSD License, see http://animista.net/license

- this software uses code
  Copyright © 2003-2007, Dr. Edmund Weitz. All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials
       provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE AUTHOR 'AS IS' AND ANY EXPRESSED
  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

- string-utils.lisp has code derived from:
  http://locutus.io/
  distributed under the follow license according to the link above

  Copyright (c) 2007-2016 Kevin van Zonneveld (http://kvz.io)
  and Contributors (http://locutus.io/authors)

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
  of the Software, and to permit persons to whom the Software is furnished to do
  so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.


- www/css/pell.css
  www/js/pell-init.js
  www/js/pell.js

  derived from

  The MIT License (MIT)

  Copyright (c) Jared Reich

  Permission  is  hereby  granted,  free  of  charge,  to  any  person
  obtaining a copy of this software and associated documentation files
  (the  "Software"),  to deal  in  the  Software without  restriction,
  including without limitation the rights to use, copy, modify, merge,
  publish, distribute, sublicense, and/or sell copies of the Software,
  and to  permit persons to whom  the Software is furnished  to do so,
  subject to the following conditions:

  The  above copyright  notice  and this  permission  notice shall  be
  included in all copies or substantial portions of the Software.

  THE  SOFTWARE IS  PROVIDED "AS  IS", WITHOUT  WARRANTY OF  ANY KIND,
  EXPRESS OR IMPLIED,  INCLUDING BUT NOT LIMITED TO  THE WARRANTIES OF
  MERCHANTABILITY,    FITNESS   FOR    A   PARTICULAR    PURPOSE   AND
  NONINFRINGEMENT. IN NO EVENT SHALL  THE AUTHORS OR COPYRIGHT HOLDERS
  BE LIABLE FOR  ANY CLAIM, DAMAGES OR OTHER LIABILITY,  WHETHER IN AN
  ACTION OF  CONTRACT, TORT OR OTHERWISE,  ARISING FROM, OUT OF  OR IN
  CONNECTION WITH  THE SOFTWARE OR  THE USE  OR OTHER DEALINGS  IN THE
  SOFTWARE.

- www/js/decode-html-entities.js
  derived from:

  https://stackoverflow.com/questions/1147359/how-to-decode-html-entities-using-jquery#1395954
  author lucascaro https://stackoverflow.com/users/428486/lucascaro
  © lucascaro released under creative commons
  Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
  https://creativecommons.org/licenses/by-sa/4.0/
