* Introduction

Niccolo' is  a web based software  aimed at safe chemicals  storage, using and
disposing.

* Building
  Niccolo' is  written in Common Lisp,  except for a couple  of library
  (written in C) it depends on.

** Dependency
*** Library
  Niccolo' depend on the following common lisp libraries:

  - alexandria;
  - cl-ppcre-unicode;
  - bordeaux-threads;
  - dbi;
  - cl-smtp;
  - cl-sanitize;
  - envy;
  - parse-number;
  - xmls;
  - html-template;
  - cl-base64;
  - osicat;
  - log4cl;
  - ironclad;
  - cl-who;
  - cl-json;
  - flexi-streams;
  - cl-gd;
  - hunchentoot;
  - drakma;
  - restas;
  - restas-directory-publisher;
  - cl-pslib;
  - cl-pslib-barcode;
  - cl-i18n;
  - crane.

  Except for  crane (see below) all  of them are  available from  quicklisp.

  For crane a patched version (available [[https://github.com/cage2/crane/tree/sqlite][here]]), is needed.

  Also be sure to install the following C libraries:

  - libgd;
  - libsqlite3;
  - pslib.

*** External programs
    - sbcl;
    - wget;
    - sqlite3;
    - screen;
    - gcc;
    - bash;
    - autotools build system (i.e. autoconf, automake etc).

** Installation

Note: Assuming directory ~/lisp exists and is writable.

Also     basic     [[https://www.common-lisp.net/project/asdf/][ASDF]] knowledge is mandatory.

Moreover  steps 6-12  should  be  skipped if  you  have quicklisp  already
installed  and  ASDF  configured  (but  you  should  install  all  the
[[Dependency]] anyway, via quicklisp).

1. cd ~/lisp/
2. wget https://beta.quicklisp.org/quicklisp.lisp
3. wget https://beta.quicklisp.org/quicklisp.lisp.asc
4. wget https://beta.quicklisp.org/release-key.txt
5. check quicklisp gpg key
5. clone niccolo repository;
6. cd niccolo
7. autoreconf -fiv
8. ./configure
9. bash ./quick_quicklisp.sh (the script will download and install most of the libraries, also will help you to configure ASDF);
10. clone [[https://github.com/cage2/crane/tree/sqlite][this version of crane]] in  ~/quicklisp/local-projects;
11. cd ~/quicklisp/dists/quicklisp/software/cl-gd-0.6.1
12. make
13. cd ~/lisp/niccolo/
14. make
15. put your ssl certificate in ssl/
16. edit config.lisp
    #+BEGIN_SRC lisp

(define-constant +path-prefix+ "/niccolo" :test #'string=)

;; ssl

(define-constant +hostname+   "xxxxxxxxx" :test #'string=)

(defparameter *ssl-certfile* (asdf:system-relative-pathname :lab #p"ssl/xxx.pem"))

(defparameter *ssl-key* (asdf:system-relative-pathname :lab #p"ssl/xxxx.pem"))

(define-constant +ssl-pass+   "xxxxxx" :test #'string=)

   #+END_SRC

17. Optional, configure this section for email notifications.

   #+BEGIN_SRC lisp
  ;; smtp config

  ;; you want  actually to use mail  notification? Set this value  to a
  ;; non nil value ('t' for example).
  (define-constant +use-smtp+            nil                 :test #'eq)

  (define-constant +smtp-host+           "localhost"         :test #'string=)

  (define-constant +smtp-from-address+   "noreply@localhost" :test #'string=)

  (define-constant +smtp-port-address+   465                 :test #'=)

  ;; '() for no authentication
  (define-constant +smtp-autentication+  '("username" "password") :test #'equalp)

  ;; use nil for no ssl
  (define-constant +smtp-ssl+             t                       :test #'string=)

  (define-constant +smtp-subject-mail-prefix+  "[niccolo] "       :test #'string=)

   #+END_SRC

18. Optional (but *strongly* recommended), use CAS autentication

   #+BEGIN_SRC lisp
;; cas config

(define-constant +cas-server-host-name+    "" :test #'string=)

(define-constant +cas-server-path-prefix+  ""    :test #'string=)
   #+END_SRC

   you need to compile mini-cas library to use this feature see: [[CAS authentication]] below.

19. Optional (but *strongly* recommended)
    If you plan to put niccolo behind a reverse proxy (and we recommend to do so) also set:

   #+BEGIN_SRC lisp
(define-constant +https-poxy-port+ -1 :test #'=)
   #+END_SRC

    to the actual port (usually 443) where your http server is listening on the internet/intranet.

20. sh start_server.sh
21. point your browser to
    https://\+hostname\+:(\+https-poxy-port\+|\+https-port\+)/\+path-prefix\+/add-admin/
    where \+hostname\+  and \+path-prefix\+ are the values  of the variables setted  in point
    19, also specify  the actual port your server is  listening on the
    internet (\+https-poxy-port\+ or \+https-port\+) to generate the administrator account.

* Authentication
 Niccolo comes with two kinds of autenthication mechanisms.

** Internal database of users
 The first is based on an table in its own database which stores username/password.

 We *does not*  recommend using this kind of authentication  as it was
 developed just for testing purposes.

** CAS authentication

   Niccolo includes a  [[https://github.com/Jasig/cas/blob/master/cas-server-documentation/protocol/CAS-Protocol-Specification.md][CAS]] client library (in  .../lib/ directory) for
   authentication, this is what we use in our production environment.

   To enable CAS  authentication just put the mini-cas  directory in a
   place where ASDF  is going to be able to  find (load, actually) it,
   niccolo will  use CAS automatically.  Then edit config.lisp  in the
   CAS section.

   If  mini-cas is  not loaded with ASDF  niccolo' will  use internal
   authentication instead.

   Please   note   that,   depending    of   the   content   of   your
   source-registry.conf  file   (expecially  if  you  use   the  :tree
   options), .../lib/mini-cas/ *will* be reached by ASDF.

* Start server
  Use the  'start_server.sh' or 'start_server-cas.sh' scripts to  start the server
  without or with CAS authentication respectively.
* BUGS

  Please send bug report to cage at katamail dot com

* License

  This  program  is Copyright  (C)  2016  Universita' degli  Studi  di
  Palermo and released under GNU General Public license version 3 (see
  COPYING file).

  The  program  use data  and  code  from  other sources,  please  see
  LICENSE.org.

  Although any efforts  has  been  put to  make  the  list of  credits
  exaustive,  errors are  always possible.  Please send  correction to
  cage at katamail dot com.

* Contributing
  Any  help  is  appreciated. Please send a message to
  cage at katamail dot com.

* NO WARRANTY

  niccolo': a chemicals inventory
  Copyright (C) 2016  Universita' degli Studi di Palermo

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
